services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8002:8000"
    env_file: ../.env
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flight_tracking_system
    ports:
      - "5433:5432"
